name: hyperion glue job

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Running Build Command"
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: deploy_to_dev
        run: echo "deploying to dev"

  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
      - name: deploy_to_prod
        run: echo "deploying to dev"

  