name: hyperion glue job

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Running Build Command"
      - name: test
        run: echo "Running tests"
      - name: fail test
        run: echhh failed
  